def get_comprehensive_metadata_retrieve_body(session_id):
    """Generate comprehensive metadata retrieve request with ALL Salesforce metadata types"""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:met="http://soap.sforce.com/2006/04/metadata">
   <soapenv:Header>
      <met:SessionHeader>
         <met:sessionId>{session_id}</met:sessionId>
      </met:SessionHeader>
   </soapenv:Header>
   <soapenv:Body>
      <met:retrieve>
         <met:retrieveRequest>
            <met:apiVersion>62.0</met:apiVersion>
            <met:singlePackage>true</met:singlePackage>
            <met:unpackaged>
               <types>
                  <members>*</members>
                  <name>ApexClass</name>
               </types>
               <types>
                  <members>*</members>
                  <name>ApexTrigger</name>
               </types>
               <types>
                  <members>*</members>
                  <name>ApexPage</name>
               </types>
               <types>
                  <members>*</members>
                  <name>ApexComponent</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomObject</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomField</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Flow</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Layout</name>
               </types>
               <types>
                  <members>*</members>
                  <name>ValidationRule</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WorkflowRule</name>
               </types>
               <types>
                  <members>*</members>
                  <name>PermissionSet</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Profile</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Role</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Group</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Queue</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomTab</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomApplication</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomPermission</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomMetadata</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomLabel</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomSite</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomWebLink</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomObjectTranslation</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomPageWebLink</name>
               </types>
               <types>
                  <members>*</members>
                  <name>CustomTabTranslation</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Dashboard</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Document</name>
               </types>
               <types>
                  <members>*</members>
                  <name>EmailTemplate</name>
               </types>
               <types>
                  <members>*</members>
                  <name>FlexiPage</name>
               </types>
               <types>
                  <members>*</members>
                  <name>GlobalValueSet</name>
               </types>
               <types>
                  <members>*</members>
                  <name>GlobalValueSetTranslation</name>
               </types>
               <types>
                  <members>*</members>
                  <name>HomePageComponent</name>
               </types>
               <types>
                  <members>*</members>
                  <name>HomePageLayout</name>
               </types>
               <types>
                  <members>*</members>
                  <name>InstalledPackage</name>
               </types>
               <types>
                  <members>*</members>
                  <name>ListView</name>
               </types>
               <types>
                  <members>*</members>
                  <name>NamedCredential</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Network</name>
               </types>
               <types>
                  <members>*</members>
                  <name>NetworkBranding</name>
               </types>
               <types>
                  <members>*</members>
                  <name>NetworkMemberGroup</name>
               </types>
               <types>
                  <members>*</members>
                  <name>NetworkPageOverride</name>
               </types>
               <types>
                  <members>*</members>
                  <name>NetworkTabSet</name>
               </types>
               <types>
                  <members>*</members>
                  <name>PathAssistant</name>
               </types>
               <types>
                  <members>*</members>
                  <name>PermissionSetGroup</name>
               </types>
               <types>
                  <members>*</members>
                  <name>PlatformEventChannel</name>
               </types>
               <types>
                  <members>*</members>
                  <name>PlatformEventChannelMember</name>
               </types>
               <types>
                  <members>*</members>
                  <name>PostTemplate</name>
               </types>
               <types>
                  <members>*</members>
                  <name>ProfilePasswordPolicy</name>
               </types>
               <types>
                  <members>*</members>
                  <name>ProfileSessionSetting</name>
               </types>
               <types>
                  <members>*</members>
                  <name>QueueRoutingConfig</name>
               </types>
               <types>
                  <members>*</members>
                  <name>QuickAction</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Report</name>
               </types>
               <types>
                  <members>*</members>
                  <name>ReportType</name>
               </types>
               <types>
                  <members>*</members>
                  <name>SamlSsoConfig</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Scontrol</name>
               </types>
               <types>
                  <members>*</members>
                  <name>ServiceChannel</name>
               </types>
               <types>
                  <members>*</members>
                  <name>ServicePresenceStatus</name>
               </types>
               <types>
                  <members>*</members>
                  <name>SharingRules</name>
               </types>
               <types>
                  <members>*</members>
                  <name>SharingSet</name>
               </types>
               <types>
                  <members>*</members>
                  <name>SiteDotCom</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Skill</name>
               </types>
               <types>
                  <members>*</members>
                  <name>StandardValueSet</name>
               </types>
               <types>
                  <members>*</members>
                  <name>StandardValueSetTranslation</name>
               </types>
               <types>
                  <members>*</members>
                  <name>StaticResource</name>
               </types>
               <types>
                  <members>*</members>
                  <name>SynonymDictionary</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Territory</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Territory2</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Territory2Model</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Territory2Rule</name>
               </types>
               <types>
                  <members>*</members>
                  <name>Territory2Type</name>
               </types>
               <types>
                  <members>*</members>
                  <name>TopicsForObjects</name>
               </types>
               <types>
                  <members>*</members>
                  <name>UserCriteria</name>
               </types>
               <types>
                  <members>*</members>
                  <name>UserProfileSearch</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WaveApplication</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WaveDashboard</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WaveDataflow</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WaveDataset</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WaveLens</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WaveRecipe</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WaveSpoke</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WaveXmd</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WorkflowAlert</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WorkflowFieldUpdate</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WorkflowKnowledgePublish</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WorkflowOutboundMessage</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WorkflowSend</name>
               </types>
               <types>
                  <members>*</members>
                  <name>WorkflowTask</name>
               </types>
               <version>62.0</version>
            </met:unpackaged>
         </met:retrieveRequest>
      </met:retrieve>
   </soapenv:Body>
</soapenv:Envelope>'''

# List of all Salesforce metadata types for reference
ALL_METADATA_TYPES = [
    'ApexClass', 'ApexTrigger', 'ApexPage', 'ApexComponent', 'CustomObject', 'CustomField',
    'Flow', 'Layout', 'ValidationRule', 'WorkflowRule', 'PermissionSet', 'Profile', 'Role',
    'Group', 'Queue', 'CustomTab', 'CustomApplication', 'CustomPermission', 'CustomMetadata',
    'CustomLabel', 'CustomSite', 'CustomWebLink', 'CustomObjectTranslation', 'CustomPageWebLink',
    'CustomTabTranslation', 'Dashboard', 'Document', 'EmailTemplate', 'FlexiPage', 'GlobalValueSet',
    'GlobalValueSetTranslation', 'HomePageComponent', 'HomePageLayout', 'InstalledPackage',
    'ListView', 'NamedCredential', 'Network', 'NetworkBranding', 'NetworkMemberGroup',
    'NetworkPageOverride', 'NetworkTabSet', 'PathAssistant', 'PermissionSetGroup',
    'PlatformEventChannel', 'PlatformEventChannelMember', 'PostTemplate', 'ProfilePasswordPolicy',
    'ProfileSessionSetting', 'QueueRoutingConfig', 'QuickAction', 'Report', 'ReportType',
    'SamlSsoConfig', 'Scontrol', 'ServiceChannel', 'ServicePresenceStatus', 'SharingRules',
    'SharingSet', 'SiteDotCom', 'Skill', 'StandardValueSet', 'StandardValueSetTranslation',
    'StaticResource', 'SynonymDictionary', 'Territory', 'Territory2', 'Territory2Model',
    'Territory2Rule', 'Territory2Type', 'TopicsForObjects', 'UserCriteria', 'UserProfileSearch',
    'WaveApplication', 'WaveDashboard', 'WaveDataflow', 'WaveDataset', 'WaveLens', 'WaveRecipe',
    'WaveSpoke', 'WaveXmd', 'WorkflowAlert', 'WorkflowFieldUpdate', 'WorkflowKnowledgePublish',
    'WorkflowOutboundMessage', 'WorkflowSend', 'WorkflowTask'
] 